version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - 7474:7474  # Neo4j 浏览器
      - 7687:7687  # Bolt 协议
    environment:
      - NEO4J_AUTH=neo4j/neo4j123456
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./data:/data
      - ./import:/import
